# Generated by Django 4.2.20 on 2025-05-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(db_column='VIN', default='asf', max_length=17, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_position',
            field=models.ForeignKey(db_column='EmployeePositionID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_site.employeeposition'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_brand',
            field=models.ForeignKey(db_column='PartBrandID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_site.partbrand'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.ForeignKey(db_column='PartTypeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_site.parttype'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='employee',
            field=models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='service_site.employee'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='order_date',
            field=models.DateTimeField(db_column='OrderDate', null=True),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='order_number',
            field=models.CharField(db_column='OrderNumber', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='procurement_status',
            field=models.ForeignKey(db_column='ProcurementStatusID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_site.procurementstatus'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='supplier',
            field=models.ForeignKey(db_column='SupplierID', on_delete=django.db.models.deletion.CASCADE, to='service_site.supplier'),
        ),
        migrations.AlterField(
            model_name='procurementorder',
            name='total_price',
            field=models.DecimalField(db_column='TotalPrice', decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procurementstatus',
            name='status_name',
            field=models.CharField(db_column='StatusName', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='procurementunit',
            name='price_per_unit',
            field=models.DecimalField(db_column='PricePerUnit', decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procurementunit',
            name='procurement_order',
            field=models.ForeignKey(db_column='ProcurementOrderID', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='service_site.procurementorder'),
        ),
        migrations.AlterField(
            model_name='providedservice',
            name='employee',
            field=models.ForeignKey(db_column='EmployeeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_site.employee'),
        ),
        migrations.AlterField(
            model_name='storageplacement',
            name='placement_date',
            field=models.DateTimeField(db_column='PlacementDate'),
        ),
        migrations.AlterField(
            model_name='storageplacement',
            name='procurement_unit',
            field=models.ForeignKey(db_column='ProcurementUnitID', on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='service_site.procurementunit'),
        ),
        migrations.AlterField(
            model_name='storageplacement',
            name='quantity',
            field=models.IntegerField(db_column='Quantity', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(db_column='SupplierName', max_length=100),
        ),
    ]
